/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import locadoraveiculos.Cliente;
import locadoraveiculos.LocadoraDados;
import locadoraveiculos.Veiculo;

/**
 *
 * @author EC_es
 */
public class CadastroDeVeiculos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDeVeiculos
     * @param indice recebe um indice para abrir no cadastro, caso seja passado -1 como parametro o cadastro será iniciado como novo
     */
    public CadastroDeVeiculos(int indice) {
        initComponents();
        
        
        if (indice == -1){
            cbDisponivel.setSelected(true);
            ajustarCampos();
            lblCodigo.setText(String.valueOf(LocadoraDados.setCodigoAutomatico()));
        }else{
            preencheCampos(indice);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        cbTipoVeiculo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValorDiaria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblNumPassageiros = new javax.swing.JLabel();
        txtNumPassageiros = new javax.swing.JTextField();
        lblPossuiPartida = new javax.swing.JLabel();
        cbPossuiPartida = new javax.swing.JComboBox<>();
        cbDisponivel = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        lblIndice = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        btListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAnterior.setText("<");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btProximo.setText(">");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        cbTipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARRO", "MOTO" }));
        cbTipoVeiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoVeiculoItemStateChanged(evt);
            }
        });
        cbTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoVeiculoActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo:");

        jLabel2.setText("Valor Diária:");

        txtValorDiaria.setText("0,00");

        jLabel3.setText("Descição:");

        jLabel4.setText("Placa:");

        lblNumPassageiros.setText("Nº Passageiros:");

        txtNumPassageiros.setText("4");

        lblPossuiPartida.setText("Partida:");

        cbPossuiPartida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO" }));

        cbDisponivel.setText("Disponível");

        jLabel5.setText("Indice:");

        lblIndice.setText("(Novo)");

        jLabel6.setText("Marca:");

        jLabel7.setText("Código:");

        lblCodigo.setText("(Novo)");

        btListar.setText("Listar");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSalvar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btListar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btProximo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIndice)))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(lblPossuiPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDescricao)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPossuiPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbDisponivel)
                                .addGap(71, 71, 71))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblNumPassageiros)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btSalvar)
                    .addComponent(btExcluir)
                    .addComponent(btAnterior)
                    .addComponent(btProximo)
                    .addComponent(btListar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblIndice)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblCodigo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lblNumPassageiros)
                    .addComponent(txtNumPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cbDisponivel))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPossuiPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPossuiPartida))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoVeiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoVeiculoItemStateChanged
        ajustarCampos();
        
    }//GEN-LAST:event_cbTipoVeiculoItemStateChanged

    private void preencheCampos(int indice){
        lblCodigo.setText(String.valueOf(LocadoraDados.getVeiculos().get(indice).getCodigoAuto()));
        cbTipoVeiculo.setSelectedItem(LocadoraDados.getVeiculos().get(indice).getTipo());
        ajustarCampos();
        txtValorDiaria.setText(String.valueOf(LocadoraDados.getVeiculos().get(indice).getValorDiaria()));
        txtDescricao.setText(String.valueOf(LocadoraDados.getVeiculos().get(indice).getDescricao()));
        txtPlaca.setText(String.valueOf(LocadoraDados.getVeiculos().get(indice).getPlaca()));
        txtNumPassageiros.setText(String.valueOf(LocadoraDados.getVeiculos().get(indice).getPassageiros()));
        cbPossuiPartida.setSelectedItem(LocadoraDados.getVeiculos().get(indice).getPartida());
        cbDisponivel.setSelected(LocadoraDados.getVeiculos().get(indice).isDisponivel());
        lblIndice.setText(String.valueOf(indice));
        txtMarca.setText(LocadoraDados.getVeiculos().get(indice).getMarca());
    }
    
    private void limpaCampos(){
        cbTipoVeiculo.setSelectedItem("CARRO");    
        ajustarCampos();
        txtValorDiaria.setText("0,00");
        txtDescricao.setText("");
        txtPlaca.setText("");
        txtNumPassageiros.setText("0");
        cbPossuiPartida.setSelectedItem("NÃO");
        cbDisponivel.setSelected(true);
        lblIndice.setText("(Novo)");
        txtMarca.setText("");
    }
    
    
    private void ajustarCampos(){
        if(cbTipoVeiculo.getSelectedItem().toString().equals("CARRO")){
            cbPossuiPartida.setVisible(false);
            lblPossuiPartida.setVisible(false);
            lblNumPassageiros.setVisible(true);
            txtNumPassageiros.setVisible(true);
        }else if(cbTipoVeiculo.getSelectedItem().toString().equals("MOTO")){
            lblNumPassageiros.setVisible(false);
            txtNumPassageiros.setVisible(false);
            cbPossuiPartida.setVisible(true);
            lblPossuiPartida.setVisible(true);
        }
    }
    
    private void cbTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoVeiculoActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        int indice;
        try{
            indice = Integer.parseInt(lblIndice.getText());
        }catch(java.lang.NumberFormatException e){
            indice = LocadoraDados.getVeiculos().size();
        }
        
    
        if (LocadoraDados.getVeiculos().size() == 0){
            JOptionPane.showMessageDialog(null, "Esse é o primeiro registro");
        }else{
            
            
            if(indice <= 0){
                JOptionPane.showMessageDialog(null, "Esse é o primeiro registro");
            }else{
                indice --;
                preencheCampos(indice);  //Chama o metodo para preencher os campos
            }
            
        }
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Veiculo veiculo = null;
        boolean dadosValidos;   
        
        try{
                veiculo = new Veiculo(
                        lblCodigo.getText(),
                        cbTipoVeiculo.getSelectedItem().toString(), 
                        txtValorDiaria.getText(), 
                        txtDescricao.getText(), 
                        txtPlaca.getText(), 
                        txtNumPassageiros.getText(),
                        cbPossuiPartida.getSelectedItem().toString(),
                        txtMarca.getText(),
                        cbDisponivel.isSelected()
                );
                
                if(veiculo.getTipo().equals("MOTO")){
                    veiculo.setPassageiros("2");
                }else{
                    veiculo.setPartida("SIM");
                }
                dadosValidos = true;
            }catch(java.lang.IllegalArgumentException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
                dadosValidos = false;
            }
        
        
        if((getIndice() == -1) && (dadosValidos == true)){
            System.out.println("Adicionar novo veiculo");
         
            lblIndice.setText(String.valueOf(LocadoraDados.getVeiculos().size()));
            LocadoraDados.cadastraVeiculo(veiculo);
        }
        
        if(getIndice() >= 0){
            System.out.println("Alterar veiculo do indice: " + getIndice());
            LocadoraDados.alteraVeiculo(getIndice(), veiculo);
            
            
        }
        
        
        
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private int getCodigo(){
        int codigo = -1;
        try{
            
            codigo = Integer.parseInt(lblCodigo.getText());
        }catch(NumberFormatException e){
            
            return -1;
        }
        return codigo;
    }
    
    private int getIndice(){
        int indice = -1;
        try{
            
            indice = Integer.parseInt(lblIndice.getText());
        }catch(NumberFormatException e){
            
            return -1;
        }
        return indice;
    }
    
    
    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        int indice;
        try{
            
            indice = Integer.parseInt(lblIndice.getText());
            
        }catch(java.lang.NumberFormatException e){
            indice = LocadoraDados.getVeiculos().size();
        }

        if(indice+1 >= LocadoraDados.getVeiculos().size()){
            JOptionPane.showMessageDialog(null, "Esse é o ultimo registro");
        }else{
            indice++;
            preencheCampos(indice);
        }
    }//GEN-LAST:event_btProximoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        
        if(lblIndice.getText().equals("(Novo)")){
            JOptionPane.showMessageDialog(null, "Não há nada para excluir");
        }else{
        
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse registro?", "Receber", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {    


                int minIndice = 0, maxIndice, indice, codigo = -1;
                maxIndice = LocadoraDados.getVeiculos().size()-1;

                try{
                    indice = Integer.parseInt(lblIndice.getText());
                    codigo = Integer.parseInt(lblCodigo.getText());
                }catch(NumberFormatException e){
                    indice = maxIndice;                        
                }

                if(LocadoraDados.verificaExclusaoVeiculo(codigo) == true){

                    if((indice >= 0) && (indice <= maxIndice)){

                        if(maxIndice>0 && indice < maxIndice){
                            LocadoraDados.removeVeiculo(indice);  
                            preencheCampos(indice);
                            
                        }else if((indice == 0) && (maxIndice == 0)){
                            LocadoraDados.removeVeiculo(indice);               
                            limpaCampos(); 
                            
                        }else if((indice == 0) && (maxIndice > 0)){

                            LocadoraDados.removeVeiculo(indice);  
                            preencheCampos(indice);
                            
                        }else if((indice == maxIndice) && (maxIndice > 0)){

                            LocadoraDados.removeVeiculo(indice);  
                            indice --;
                            preencheCampos(indice);
                            
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Desculpe, esse veiculo não pode ser excluido, pois existem alugueis vinculados a ale");
                }
            }else{

            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        limpaCampos();
        lblCodigo.setText(String.valueOf(LocadoraDados.setCodigoAutomatico()));
        
    }//GEN-LAST:event_btNovoActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        listarVeiculos = new ListarVeiculos();
        listarVeiculos.setLocationRelativeTo(null);
        listarVeiculos.setVisible(true);
    }//GEN-LAST:event_btListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeVeiculos(-1).setVisible(true);
            }
        });
    }
    private ListarVeiculos listarVeiculos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox cbDisponivel;
    private javax.swing.JComboBox<String> cbPossuiPartida;
    private javax.swing.JComboBox<String> cbTipoVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblIndice;
    private javax.swing.JLabel lblNumPassageiros;
    private javax.swing.JLabel lblPossuiPartida;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNumPassageiros;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtValorDiaria;
    // End of variables declaration//GEN-END:variables
}
