/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import locadoraveiculos.Cliente;
import locadoraveiculos.LocacaoVeiculo;
import locadoraveiculos.LocadoraDados;
import locadoraveiculos.Veiculo;

/**
 *
 * @author EC_es
 */
public class LocarVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form LocarVeiculo
     */

    
    public LocarVeiculo() {
      
        initComponents();
        
        for (int i=0; i < LocadoraDados.getClientes().size(); i++) {            
         comboCliente.addItem(LocadoraDados.getClientes().get(i).getNome()+ " | " + String.valueOf(LocadoraDados.getClientes().get(i).getID())); 
         
        }
        
        for (int i=0; i < LocadoraDados.getVeiculos().size(); i++) {            
         comboVeiculo.addItem(LocadoraDados.getVeiculos().get(i).getDescricao()+ " | " + String.valueOf(LocadoraDados.getVeiculos().get(i).getCodigoAuto())); 
         
        }
        //comboCliente.setSelectedItem(null);
        //comboVeiculo.setSelectedItem(null);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboCliente = new javax.swing.JComboBox<>();
        txtDias = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDataInicial = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDataFinal = new javax.swing.JFormattedTextField();
        cbSeguro = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        comboVeiculo = new javax.swing.JComboBox<>();
        btCadastro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblIndice = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtValorDiaria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtValorDesconto = new javax.swing.JTextField();
        lblCli = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtValorSeguro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNumPassageiros = new javax.swing.JTextField();
        txtTipoVeiculo = new javax.swing.JLabel();
        lblPossuiPartida = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btExcliur = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btNova = new javax.swing.JButton();
        btReceber = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btProximo = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        txtValorTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDescontoReal = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblTotalSeguro = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTotalDiaria = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        comboCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboClienteItemStateChanged(evt);
            }
        });
        comboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClienteActionPerformed(evt);
            }
        });

        txtDias.setEditable(false);
        txtDias.setText("1");

        jLabel1.setText("Cliente:");

        jLabel2.setText("Dias:");

        txtDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataInicialActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Inicial:");

        jLabel4.setText("Data Final:");

        txtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDataFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataFinalFocusLost(evt);
            }
        });
        txtDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataFinalActionPerformed(evt);
            }
        });

        cbSeguro.setText("Adicionar seguro");

        jLabel5.setText("Veículo");

        comboVeiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboVeiculoItemStateChanged(evt);
            }
        });
        comboVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboVeiculoMouseClicked(evt);
            }
        });
        comboVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVeiculoActionPerformed(evt);
            }
        });

        btCadastro.setText("Cadastro");
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });

        jLabel8.setText("Indice:");

        lblIndice.setText("(Novo)");

        jLabel9.setText("Valor Diária:");

        txtValorDiaria.setEditable(false);
        txtValorDiaria.setText("0,00");

        jLabel10.setText("Desconto %:");

        txtValorDesconto.setText("0,00");

        lblCli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCli.setToolTipText("");

        jLabel7.setText("R$ Seguro dia:");

        txtValorSeguro.setEditable(false);
        txtValorSeguro.setText("0,00");

        jLabel11.setText("Nº Passageiros:");

        txtNumPassageiros.setEditable(false);
        txtNumPassageiros.setText("0");

        txtTipoVeiculo.setText("(Tipo)");

        lblPossuiPartida.setText("(Partida)");

        btExcliur.setText("Excluir");
        btExcliur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcliurActionPerformed(evt);
            }
        });

        btSalvar.setBackground(new java.awt.Color(51, 153, 255));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btNova.setText("Nova");
        btNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovaActionPerformed(evt);
            }
        });

        btReceber.setBackground(new java.awt.Color(51, 255, 51));
        btReceber.setText("Receber");
        btReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceberActionPerformed(evt);
            }
        });

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNova)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcliur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(215, 215, 215)
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btReceber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNova)
                    .addComponent(btSalvar)
                    .addComponent(btExcliur)
                    .addComponent(btReceber)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("Possui Partida:");

        jLabel13.setText("Status:");

        lblStatus.setText("(Não Deifinido)");

        jLabel14.setText("Dados do Cliente");

        jLabel17.setText("Dados do Veículo");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btProximo.setText(">");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        btAnterior.setText("<");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        txtValorTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtValorTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtValorTotal.setText("0,00");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor Total:");

        lblDescontoReal.setForeground(new java.awt.Color(255, 255, 255));
        lblDescontoReal.setText("0,00");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Desconto R$");

        lblTotalSeguro.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalSeguro.setText("0,00");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total seguro:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total Diária:");

        lblTotalDiaria.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalDiaria.setText("0,00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProximo)
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescontoReal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btProximo)
                    .addComponent(btAnterior)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(lblTotalSeguro)
                        .addComponent(jLabel18)
                        .addComponent(lblDescontoReal)
                        .addComponent(lblTotalDiaria)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtValorTotal))
                .addContainerGap())
        );

        jLabel19.setText("Dados do aluguel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4))
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIndice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboVeiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadastro)
                        .addContainerGap())
                    .addComponent(lblCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPossuiPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDataFinal)
                                    .addComponent(txtValorSeguro, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtValorDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(txtDias))
                                .addGap(18, 18, 18)
                                .addComponent(cbSeguro)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblIndice)
                    .addComponent(jLabel13)
                    .addComponent(lblStatus))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCli, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNumPassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPossuiPartida)
                    .addComponent(txtTipoVeiculo)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtValorDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtValorSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSeguro))
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicialActionPerformed

    private void txtDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFinalActionPerformed

    private void comboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClienteActionPerformed
        
    }//GEN-LAST:event_comboClienteActionPerformed

    private void txtDataFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFinalFocusLost
        //23/11/2018
        
        try{
            int di, mi, ai;
            di = Integer.parseInt(txtDataInicial.getText().substring(0, 2));
            mi = Integer.parseInt(txtDataInicial.getText().substring(3, 5));
            ai = Integer.parseInt(txtDataInicial.getText().substring(6, 10));
            System.out.println(di+"-"+mi+"-"+ai);

            int df, mf, af;
            df = Integer.parseInt(txtDataFinal.getText().substring(0, 2));
            mf = Integer.parseInt(txtDataFinal.getText().substring(3, 5));
            af = Integer.parseInt(txtDataFinal.getText().substring(6, 10));
        
            System.out.println(df+"-"+mf+"-"+ai);

            LocalDate inicio = LocalDate.of(ai, mi, di);
            LocalDate fim = LocalDate.of(af, mf, df);
            int intervalo = (int) ChronoUnit.DAYS.between(inicio, fim);
            
            if(intervalo < 0){
                JOptionPane.showMessageDialog(null, "A data inicial deve ser menor que a final");
                txtDias.setText("");
            }else{
                txtDias.setText(String.valueOf(intervalo));
            }
            
            
        }catch(java.lang.StringIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Datas inválidas");
            txtDias.setText("");
        }catch(java.time.DateTimeException e){
            JOptionPane.showMessageDialog(null, "Formato de data inválido");
            txtDias.setText("");
        }
        
        
        
    }//GEN-LAST:event_txtDataFinalFocusLost

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        int i = comboCliente.getSelectedIndex();
        int indiceLoc = LocadoraDados.getLocacao().size();
        
        boolean dadosValidos;
        LocacaoVeiculo loc = null;
        int j = comboVeiculo.getSelectedIndex();
        
        if(LocadoraDados.getClientes().size() == 0){
            JOptionPane.showMessageDialog(null, "Cadastre um cliente e tente novamente");
        }else if(LocadoraDados.getVeiculos().size() == 0){
            JOptionPane.showMessageDialog(null, "Cadastre um veículo e tente novamente");        
        }else{
        
        
            Cliente cli;
            cli = new Cliente(LocadoraDados.getClientes().get(i).getNome(),
                    String.valueOf(LocadoraDados.getClientes().get(i).getID()),
                    LocadoraDados.getClientes().get(i).getEndereco(), 
                    LocadoraDados.getClientes().get(i).getTel());



            

            Veiculo veiculo;
            veiculo = new Veiculo(
                    String.valueOf(LocadoraDados.getVeiculos().get(j).getCodigoAuto()),
                    LocadoraDados.getVeiculos().get(j).getTipo(),
                    String.valueOf(LocadoraDados.getVeiculos().get(j).getValorDiaria()),
                    LocadoraDados.getVeiculos().get(j).getDescricao(),
                    LocadoraDados.getVeiculos().get(j).getPlaca(),
                    String.valueOf(LocadoraDados.getVeiculos().get(j).getPassageiros()),
                    LocadoraDados.getVeiculos().get(j).getPartida(),
                    LocadoraDados.getVeiculos().get(j).getMarca(),
                    LocadoraDados.getVeiculos().get(j).isDisponivel()

            );
            
                
                try{ 
                loc = new LocacaoVeiculo(veiculo,
                                         cli,
                                         txtValorDiaria.getText(),
                                         txtDias.getText(),
                                         txtValorDesconto.getText(),
                                         false,
                                         txtDataInicial.getText(),
                                         txtDataFinal.getText(),
                                         cbSeguro.isSelected()

                );
                loc.setStatus("LOCADO"); //Status da locação
                dadosValidos = true;
           }catch(IllegalArgumentException e){
               JOptionPane.showMessageDialog(null, e.getMessage());
               dadosValidos = false;
           }
          
           if(dadosValidos == true){     
                try{
                     if(LocadoraDados.getVeiculos().get(j).isDisponivel() == false){
                        throw new IllegalArgumentException("Este veículo não está disponível");

                     }else{
                         LocadoraDados.baixaVeiculo(j);
                     }
                 }catch(IllegalArgumentException e){
                     JOptionPane.showMessageDialog(null, e.getMessage());
                     dadosValidos = false;
                 }
            }    

           if(dadosValidos == true){
               
               LocadoraDados.cadastraLocacao(loc);
               lblIndice.setText(String.valueOf(LocadoraDados.getLocacao().size()));
               preencheCampos(indiceLoc);
           }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    
    
    /**
     * 
     * @return Retorna true: Caso o statos estja como LOCADO e False caso não esteja locado
     */
    private boolean checaStatusLocacao(){
        
        if(LocadoraDados.getLocacao().get(getIndice()).getStatus().equals("LOCADO")){
            return true;
        }else{
            return false;
        }
    }
    
    
    private void comboClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboClienteItemStateChanged
        
    }//GEN-LAST:event_comboClienteItemStateChanged

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        int indice;
        try{
             indice = Integer.parseInt(lblIndice.getText());
        }catch(java.lang.NumberFormatException e){
            indice = LocadoraDados.getLocacao().size();            
        }
        
        if(indice+1 >= LocadoraDados.getLocacao().size()){
            JOptionPane.showMessageDialog(null, "Esse é o ultimo registro");
        }else{
            indice++;
            preencheCampos(indice);
        }
        
    }//GEN-LAST:event_btProximoActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
       
        int indice;
        try{
            indice = Integer.parseInt(lblIndice.getText());
        }catch(java.lang.NumberFormatException e){
            indice = LocadoraDados.getLocacao().size();
        }
        
    
        if (LocadoraDados.getLocacao().size() == 0){
            JOptionPane.showMessageDialog(null, "Esse é o primeiro registro");
        }else{
            
            
            if(indice <= 0){
                JOptionPane.showMessageDialog(null, "Esse é o primeiro registro");
            }else{
                indice --;
                preencheCampos(indice);  //Chama o metodo para preencher os campos
            }
        } 
        
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void comboVeiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboVeiculoItemStateChanged
        int i = comboVeiculo.getSelectedIndex();
        
        txtValorDiaria.setText(String.valueOf(LocadoraDados.getVeiculos().get(i).getValorDiaria()));
        txtNumPassageiros.setText(String.valueOf(LocadoraDados.getVeiculos().get(i).getPassageiros()));
        txtTipoVeiculo.setText(LocadoraDados.getVeiculos().get(i).getTipo());
        lblPossuiPartida.setText(LocadoraDados.getVeiculos().get(i).getPartida());
        //preencheCampos(i);
    }//GEN-LAST:event_comboVeiculoItemStateChanged

    private void btNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovaActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btNovaActionPerformed

    private void comboVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVeiculoActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        cadastroDeVeiculos = new CadastroDeVeiculos(comboVeiculo.getSelectedIndex());
        cadastroDeVeiculos.setVisible(true);
        cadastroDeVeiculos.setLocationRelativeTo(null);
    }//GEN-LAST:event_btCadastroActionPerformed

    private void comboVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboVeiculoMouseClicked
       
    }//GEN-LAST:event_comboVeiculoMouseClicked

    private void btReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReceberActionPerformed
 
    if(LocadoraDados.getClientes().size() == 0){
            JOptionPane.showMessageDialog(null, "Cadastre um cliente e tente novamente");
        }else if(LocadoraDados.getVeiculos().size() == 0){
            JOptionPane.showMessageDialog(null, "Cadastre um veículo e tente novamente");
        }else if(getIndice() == -1){
            JOptionPane.showMessageDialog(null, "Essa locação não foi finalizada");
        }else if(LocadoraDados.getLocacao().get(getIndice()).getStatus().equals("RECEBIDO")){
              JOptionPane.showMessageDialog(null, "Essa locação já foi baixada");      
        }else{    
        
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente confirmar o recebimento do veículo?", "Receber", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                if(checaStatusLocacao()){
                    LocadoraDados.getLocacao().get(getIndice()).setStatus("RECEBIDO");
                    int indiceVeiculo = LocadoraDados.localizaVeiculoPorCodigo(LocadoraDados.getLocacao().get(getIndice()).getVeiculo().getCodigoAuto());  //Pegando o código do veiculo
                    if(indiceVeiculo == -1){
                        
                    }else{
                        LocadoraDados.getVeiculos().get(indiceVeiculo).setDisponivel(true);
                    }
                    preencheCampos(getIndice());
                }else{
                    //CASO FALSE
                }
            }
        }
    }//GEN-LAST:event_btReceberActionPerformed

    private void DisponibilizaVeiculo(){
        int indiceVeiculo = LocadoraDados.localizaVeiculoPorCodigo(LocadoraDados.getLocacao().get(getIndice()).getVeiculo().getCodigoAuto());  //Pegando o código do veiculo
            System.out.println("Disponibilizar o veiculo do indice: "+ indiceVeiculo);
            if(indiceVeiculo == -1){
                        
            }else{
                LocadoraDados.getVeiculos().get(indiceVeiculo).setDisponivel(true);
            }
    }
    
    
    private void btExcliurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcliurActionPerformed
                
        if(lblIndice.getText().equals("(Novo)")){
            
        }else{
        
            int minIndice = 0, maxIndice, indice;
            maxIndice = LocadoraDados.getVeiculos().size()-1;
            System.out.print(maxIndice);
            try{
                indice = Integer.parseInt(lblIndice.getText());
            }catch(NumberFormatException e){
                indice = maxIndice;                        
            }
            if((indice >= 0) && (indice <= maxIndice)){

                if(maxIndice>0 && indice < maxIndice){
                    DisponibilizaVeiculo();
                    LocadoraDados.removeLocacao(indice);  
                    limpaCampos();   
                }

                if((indice == 0) && (maxIndice == 0)){
                    DisponibilizaVeiculo();
                    LocadoraDados.removeLocacao(indice);               
                    limpaCampos();                
                }



                if((indice == maxIndice) && (maxIndice > 0)){
                    DisponibilizaVeiculo();
                    LocadoraDados.removeLocacao(indice);  
                    indice --;
                    preencheCampos(indice);
                }
            }
        
        } 
    }//GEN-LAST:event_btExcliurActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        listarLocacoes = new ListarLocacoes();
        listarLocacoes.setLocationRelativeTo(null);
        listarLocacoes.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void limpaCampos(){
        
        txtDataInicial.setText(null);
        txtDataFinal.setText(null);
        txtDias.setText("1");
        txtValorDesconto.setText("0,00");
        txtValorDiaria.setText("0,00");
        cbSeguro.setSelected(false);
        txtValorTotal.setText("0,00");
        lblIndice.setText("(Novo)");
        lblStatus.setText("(Não Definido)");
       
        
    }
    
    private int getIndice(){
        int indice = -1;
        try{
            indice = Integer.parseInt(lblIndice.getText());
        }catch(NumberFormatException e){
            
            return -1;
        }
        return indice;
    }
    
    
    private void preencheCampos(int indice){
        DecimalFormat df = new DecimalFormat("0.00");
        df.setRoundingMode(RoundingMode.HALF_DOWN);
        
        
        comboCliente.setSelectedItem(LocadoraDados.getLocacao().get(indice).getCliente().getNome() +" | " +LocadoraDados.getLocacao().get(indice).getCliente().getID());
        lblIndice.setText(String.valueOf(indice));
        lblCli.setText(LocadoraDados.getLocacao().get(indice).getCliente().getNome() +" | ID: " +LocadoraDados.getLocacao().get(indice).getCliente().getID());
        comboVeiculo.setSelectedItem(LocadoraDados.getLocacao().get(indice).getVeiculo().getDescricao()+ " | " + String.valueOf(LocadoraDados.getLocacao().get(indice).getVeiculo().getCodigoAuto()));
        txtDataInicial.setText(LocadoraDados.getLocacao().get(indice).getDataIni());
        txtDataFinal.setText(LocadoraDados.getLocacao().get(indice).getDataFin());
        txtDias.setText(String.valueOf(LocadoraDados.getLocacao().get(indice).getDias()));
        txtValorDiaria.setText(String.valueOf(LocadoraDados.getLocacao().get(indice).getVeiculo().getValorDiaria()));
        cbSeguro.setSelected(LocadoraDados.getLocacao().get(indice).isPossuiSeguro());
        txtValorTotal.setText(String.valueOf(df.format(LocadoraDados.getLocacao().get(indice).getValorLocacao()))); //O valor é arredondado
        txtValorSeguro.setText(String.valueOf(df.format(LocadoraDados.getLocacao().get(indice).getValorSeguro())));  //O valor é arredondado
        txtValorDesconto.setText(String.valueOf(df.format(LocadoraDados.getLocacao().get(indice).getDesconto()))); //O valor é arredondado
        lblStatus.setText(LocadoraDados.getLocacao().get(indice).getStatus());
        
        double totalDia = LocadoraDados.getLocacao().get(indice).getValorDiaria() * LocadoraDados.getLocacao().get(indice).getDias();
        double totalSeguro = LocadoraDados.getLocacao().get(indice).getValorSeguro() * LocadoraDados.getLocacao().get(indice).getDias();
        double totalBruto = totalDia + totalSeguro;
        
        lblTotalDiaria.setText(df.format(LocadoraDados.getLocacao().get(indice).getDias() * LocadoraDados.getLocacao().get(indice).getVeiculo().getValorDiaria()));
        lblTotalSeguro.setText(df.format(LocadoraDados.getLocacao().get(indice).getDias() * LocadoraDados.getLocacao().get(indice).getValorSeguro()));
        lblDescontoReal.setText(df.format(totalBruto * (LocadoraDados.getLocacao().get(indice).getDesconto()/100)));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocarVeiculo().setVisible(true);
            }
        });
    }
    private CadastroDeVeiculos cadastroDeVeiculos;
    private ListarLocacoes listarLocacoes;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btExcliur;
    private javax.swing.JButton btNova;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btReceber;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox cbSeguro;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JComboBox<String> comboVeiculo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblCli;
    private javax.swing.JLabel lblDescontoReal;
    private javax.swing.JLabel lblIndice;
    private javax.swing.JLabel lblPossuiPartida;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotalDiaria;
    private javax.swing.JLabel lblTotalSeguro;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtNumPassageiros;
    private javax.swing.JLabel txtTipoVeiculo;
    private javax.swing.JTextField txtValorDesconto;
    private javax.swing.JTextField txtValorDiaria;
    private javax.swing.JTextField txtValorSeguro;
    private javax.swing.JLabel txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
