/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import locadoraveiculos.Cliente;
import locadoraveiculos.LocadoraDados;
import locadoraveiculos.Veiculo;

/**
 *
 * @author renan
 */
public class MenuCentral extends javax.swing.JFrame {

    /**
     * Creates new form MenuCentral
     */
    public MenuCentral() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btClientes = new javax.swing.JButton();
        btVeiculos = new javax.swing.JButton();
        btLocar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Locadora");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        btClientes.setText("Clientes");
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });

        btVeiculos.setText("Veículos");
        btVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVeiculosActionPerformed(evt);
            }
        });

        btLocar.setText("Locar");
        btLocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocarActionPerformed(evt);
            }
        });

        jLabel1.setText("Projeto: METODOLOGIA E LINGUAGEM DE PROGRAMAÇÃO");

        jLabel2.setText("Professor: Rodrigo Fujioka");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        
        cadastroDeCliente = new CadastroDeCliente();
        System.out.println("JANELA FECHADA");
        cadastroDeCliente.setTitle("Cadastro de Clientes");
        cadastroDeCliente.setLocationRelativeTo(null); 
        cadastroDeCliente.setAlwaysOnTop(true);
        cadastroDeCliente.setVisible(true);
            
       
          
        
        
    }//GEN-LAST:event_btClientesActionPerformed

    private void btLocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocarActionPerformed
        locarVeiculo = new LocarVeiculo();
        locarVeiculo.setLocationRelativeTo(null);  
        locarVeiculo.setTitle("Locar Veículo");
        locarVeiculo.setVisible(true);
    }//GEN-LAST:event_btLocarActionPerformed

    private void btVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVeiculosActionPerformed
        cadastrarVeiculo = new CadastroDeVeiculos(-1);
        cadastrarVeiculo.setLocationRelativeTo(null);
        cadastrarVeiculo.setTitle("Cadastrar Veículo");
        cadastrarVeiculo.setVisible(true);
    }//GEN-LAST:event_btVeiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        MenuCentral menuCentral;
        menuCentral = new MenuCentral();
        menuCentral.setLocationRelativeTo(null);  
        menuCentral.setVisible(true);
        
        
        Veiculo veiculo = new Veiculo("0", "CARRO", "50.00", "FOX 2016 4P FLEX PRETO", "MOS3422", "4", "SIM", "WOLKSWAGEN", true);
        LocadoraDados.cadastraVeiculo(veiculo);
        
        veiculo = new Veiculo("0", "CARRO", "30.00", "UNO 2P BRANCO 2009", "RES0021", "4", "SIM", "FIAT", true);
        LocadoraDados.cadastraVeiculo(veiculo);
        
        veiculo = new Veiculo("0", "MOTO", "34.00", "CG TITTAN 160 2016 PRETA", "UNH8906", "2", "NÃO", "HONDA", true);
        LocadoraDados.cadastraVeiculo(veiculo);
        
        veiculo = new Veiculo("0", "CARRO", "120.00", "DOBLO PRATA 2017", "KDK8675", "8", "SIM", "FIAT", true);
        LocadoraDados.cadastraVeiculo(veiculo);
        
        veiculo = new Veiculo("0", "MOTO", "18.00", "POP 100 LARANJA 2012", "UNH86000", "2", "NÃO", "HONDA", true);
        LocadoraDados.cadastraVeiculo(veiculo);
        
        veiculo = new Veiculo("0", "CARRO", "110.00", "SPIN BRANCA 2015 CB AUTOMATICO", "RVE3712", "7", "SIM", "CHEVROLET", true);
        LocadoraDados.cadastraVeiculo(veiculo);
         
        Cliente cliente = new Cliente("ANA PAULA RODRIGUES", "1", "RUA JOÃO MARIA DE ARAUJO - CENTRO - JOÃO PESSOA - PB", "9932-3344");
        LocadoraDados.cadastraCliente(cliente);  
        
        cliente = new Cliente("JEFFERSON ANDRÉ DA SILVA", "2", "RUA IEDA RODRIGUES DA ROCHA - CENTRO - MOSSORÓ - RN", "9000-0000");
        LocadoraDados.cadastraCliente(cliente);
    }

    private CadastroDeCliente cadastroDeCliente;
    private LocarVeiculo locarVeiculo;
    private CadastroDeVeiculos cadastrarVeiculo;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btLocar;
    private javax.swing.JButton btVeiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
