/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceUsuario;

import java.util.Locale;
import javax.swing.JOptionPane;
import locadoraveiculos.Cliente;
import locadoraveiculos.LocadoraDados;

/**
 *
 * @author renan
 */
public class Clientes extends javax.swing.JInternalFrame {

    private ListarClientes listaClientes;
    
    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        lblIndice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btListaClientes = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        btnProximo = new javax.swing.JButton();
        txtTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnPrimeiro = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        painelPrincipal.setLayout(null);

        lblIndice.setText("(Novo)");
        painelPrincipal.add(lblIndice);
        lblIndice.setBounds(100, 70, 33, 14);

        jLabel5.setText("Telefone:");
        painelPrincipal.add(jLabel5);
        jLabel5.setBounds(0, 210, 46, 14);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        painelPrincipal.add(btnExcluir);
        btnExcluir.setBounds(190, 30, 63, 23);

        btnUltimo.setText(">>");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        painelPrincipal.add(btnUltimo);
        btnUltimo.setBounds(550, 30, 49, 23);

        jLabel2.setText("ID:");
        painelPrincipal.add(jLabel2);
        jLabel2.setBounds(0, 110, 15, 14);

        btListaClientes.setText("Listar Clientes");
        btListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaClientesActionPerformed(evt);
            }
        });
        painelPrincipal.add(btListaClientes);
        btListaClientes.setBounds(260, 30, 99, 23);

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        painelPrincipal.add(btnAnterior);
        btnAnterior.setBounds(470, 30, 41, 23);
        painelPrincipal.add(txtNome);
        txtNome.setBounds(60, 140, 559, 20);

        jLabel3.setText("Nome:");
        painelPrincipal.add(jLabel3);
        jLabel3.setBounds(0, 140, 31, 14);
        painelPrincipal.add(txtEndereco);
        txtEndereco.setBounds(60, 170, 559, 20);

        btnProximo.setText(">");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        painelPrincipal.add(btnProximo);
        btnProximo.setBounds(510, 30, 41, 23);
        painelPrincipal.add(txtTelefone);
        txtTelefone.setBounds(60, 200, 559, 20);

        jLabel4.setText("Endereço:");
        painelPrincipal.add(jLabel4);
        jLabel4.setBounds(0, 170, 49, 14);

        txtId.setEditable(false);
        painelPrincipal.add(txtId);
        txtId.setBounds(60, 110, 126, 20);

        btnPrimeiro.setText("<<");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });
        painelPrincipal.add(btnPrimeiro);
        btnPrimeiro.setBounds(420, 30, 49, 23);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        painelPrincipal.add(btnNovo);
        btnNovo.setBounds(60, 30, 57, 23);

        jLabel1.setText("Índice:");
        painelPrincipal.add(jLabel1);
        jLabel1.setBounds(60, 70, 33, 14);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        painelPrincipal.add(btnSalvar);
        btnSalvar.setBounds(120, 30, 63, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        if(LocadoraDados.getClientes().size() == 0){
            JOptionPane.showMessageDialog(null, "Não há cadastros ainda");
        }else{
            preencheCampos(LocadoraDados.getClientes().size()-1);
        }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaClientesActionPerformed
        listaClientes = new ListarClientes();
        getParent().add(listaClientes);
        listaClientes.setVisible(true);
    }//GEN-LAST:event_btListaClientesActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        limpaCampos();
        txtId.setText(String.valueOf(LocadoraDados.setIdAuto()));
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if(txtId.getText().equals("")){
            txtId.setText(String.valueOf(LocadoraDados.setIdAuto()));
        }

        Cliente cli = new Cliente();
        String id, nome, endereco, telefone;
        boolean dadosValidos;

        try{
            cli = new Cliente(txtNome.getText(), txtId.getText(), txtEndereco.getText(), txtTelefone.getText());
            dadosValidos = true;
        }catch(java.lang.IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            dadosValidos = false;
        }

        if(getIndice() == -1){
           

            if(dadosValidos == true){
                lblIndice.setText(String.valueOf(LocadoraDados.getClientes().size()));
                LocadoraDados.cadastraCliente(cli);

            }
        }else{
            
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja alterar os dados?", "Confirmar ação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                
                
                LocadoraDados.alteraCliente(getIndice(), cli);
            }else{
                preencheCampos(getIndice());
            }
        }

        //lblIndice.setText(String.valueOf(LocadoraDados.getClientes().size()-1));
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if(lblIndice.getText().equals("(Novo)")){
            JOptionPane.showMessageDialog(null, "Não há nada para excluir");
        }else{

            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse registro?", "Receber", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {

                int minIndice = 0, maxIndice, indice;
                maxIndice = LocadoraDados.getClientes().size()-1;
                
                try{
                    indice = Integer.parseInt(lblIndice.getText());
                }catch(NumberFormatException e){
                    indice = maxIndice;
                }
                if((indice >= 0) && (indice <= maxIndice)){

                    if(maxIndice>0 && indice < maxIndice){

                        LocadoraDados.removeCliente(indice);
                        preencheCampos(indice);
                    }else if((indice == 0) && (maxIndice == 0)){

                        LocadoraDados.removeCliente(indice);
                        limpaCampos();
                    }else if((indice == 0) && (maxIndice > 0)){

                        LocadoraDados.removeCliente(indice);
                        preencheCampos(indice);
                    }else if((indice == maxIndice) && (maxIndice > 0)){

                        LocadoraDados.removeCliente(indice);
                        indice --;
                        preencheCampos(indice);
                    }
                }
            }else{

            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        int indice;
        try{
            indice = Integer.parseInt(lblIndice.getText());
        }catch(java.lang.NumberFormatException e){
            indice = LocadoraDados.getClientes().size();
        }

        if (LocadoraDados.getClientes().size() == 0){
            JOptionPane.showMessageDialog(null, "Esse é o primeiro registro");
        }else{

            if(indice <= 0){
                JOptionPane.showMessageDialog(null, "Esse é o primeiro registro");
            }else{
                indice --;
                preencheCampos(indice);  //Chama o metodo para preencher os campos
            }

        }

    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        int indice;
        try{

            indice = Integer.parseInt(lblIndice.getText());

        }catch(java.lang.NumberFormatException e){
            indice = LocadoraDados.getClientes().size();
        }

        if(indice+1 >= LocadoraDados.getClientes().size()){
            JOptionPane.showMessageDialog(null, "Esse é o ultimo registro");
        }else{
            indice++;
            preencheCampos(indice);
        }

    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        if(LocadoraDados.getClientes().size() == 0){
            JOptionPane.showMessageDialog(null, "Não há cadastros ainda");
        }else{
            preencheCampos(0);
        }
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        
    }//GEN-LAST:event_formInternalFrameClosed

    
    private void preencheCampos(int indice){
        if(indice < 0){
        }else{
            txtId.setText(String.valueOf(LocadoraDados.getClientes().get(indice).getID()));
            txtNome.setText(String.valueOf(LocadoraDados.getClientes().get(indice).getNome()));
            txtEndereco.setText(String.valueOf(LocadoraDados.getClientes().get(indice).getEndereco()));
            txtTelefone.setText(String.valueOf(LocadoraDados.getClientes().get(indice).getTel()));
            lblIndice.setText(String.valueOf(indice));
        }
    }
    
    
    private void limpaCampos(){
        txtId.setText("");
        txtNome.setText("");
        txtEndereco.setText("");
        txtTelefone.setText("");
        lblIndice.setText("(Novo)");
    }
    
    private int getIndice(){
        int indice = -1;
        try{
            indice = Integer.parseInt(lblIndice.getText());
        }catch(NumberFormatException e){
            
            return -1;
        }
        return indice;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btListaClientes;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblIndice;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
