/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceUsuario;

import java.math.RoundingMode;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
import locadoraveiculos.LocadoraDados;

/**
 *
 * @author EC_es
 */
public class ListarVeiculos extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    
    /**
     * Creates new form ListarVeiculos
     */
    public ListarVeiculos() {
        initComponents();
        
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Tipo");
        modelo.addColumn("Valor Dia R$");
        modelo.addColumn("Descrição");
        modelo.addColumn("Placa");
        modelo.addColumn("Marca");
        modelo.addColumn("Passageiros");
        modelo.addColumn("Possui partida");
        modelo.addColumn("Disponível");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVeiculos = new javax.swing.JTable();
        btTodos = new javax.swing.JButton();
        btLocados = new javax.swing.JButton();
        btDisponiveis = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Listar Veiculos");

        tabelaVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaVeiculos);

        btTodos.setText("Todos");
        btTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTodosActionPerformed(evt);
            }
        });

        btLocados.setText("Locados");
        btLocados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocadosActionPerformed(evt);
            }
        });

        btDisponiveis.setText("Disponíveis");
        btDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDisponiveisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(btTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLocados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDisponiveis)
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTodos)
                    .addComponent(btLocados)
                    .addComponent(btDisponiveis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTodosActionPerformed
        modelo.setNumRows(0);
        String status;
        for (int i = 0; i< LocadoraDados.getVeiculos().size(); i++){
            DecimalFormat df = new DecimalFormat("0.00");
            df.setRoundingMode(RoundingMode.HALF_DOWN);
           
       
            
        if(LocadoraDados.getVeiculos().get(i).isDisponivel() == true){
            status = "DISPONIVEL";
        }else{
            status = "INDISPONIVEL";
        }
            modelo.addRow(new String[]{ 
                String.valueOf(LocadoraDados.getVeiculos().get(i).getCodigoAuto()),
                LocadoraDados.getVeiculos().get(i).getTipo(),
                String.valueOf(df.format(LocadoraDados.getVeiculos().get(i).getValorDiaria())),
                LocadoraDados.getVeiculos().get(i).getDescricao(),
                LocadoraDados.getVeiculos().get(i).getPlaca(),
                LocadoraDados.getVeiculos().get(i).getMarca(),
                String.valueOf(LocadoraDados.getVeiculos().get(i).getPassageiros()),
                LocadoraDados.getVeiculos().get(i).getPartida(),
                status
            
            });
        }
        
        
        tabelaVeiculos.setModel(modelo);
    }//GEN-LAST:event_btTodosActionPerformed

    private void btLocadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocadosActionPerformed
       modelo.setNumRows(0);
        String status;
        for (int i = 0; i< LocadoraDados.getVeiculos().size(); i++){
                DecimalFormat df = new DecimalFormat("0.00");
                df.setRoundingMode(RoundingMode.HALF_DOWN);


            if(LocadoraDados.getVeiculos().get(i).isDisponivel() == false){

                modelo.addRow(new String[]{ 
                    String.valueOf(LocadoraDados.getVeiculos().get(i).getCodigoAuto()),
                    LocadoraDados.getVeiculos().get(i).getTipo(),
                    String.valueOf(df.format(LocadoraDados.getVeiculos().get(i).getValorDiaria())),
                    LocadoraDados.getVeiculos().get(i).getDescricao(),
                    LocadoraDados.getVeiculos().get(i).getPlaca(),
                    LocadoraDados.getVeiculos().get(i).getMarca(),
                    String.valueOf(LocadoraDados.getVeiculos().get(i).getPassageiros()),
                    LocadoraDados.getVeiculos().get(i).getPartida(),
                    "INDISPONIVEL"

                });
            }
        }   
        
        tabelaVeiculos.setModel(modelo);
    }//GEN-LAST:event_btLocadosActionPerformed

    private void btDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDisponiveisActionPerformed
        modelo.setNumRows(0);
        String status;
        for (int i = 0; i< LocadoraDados.getVeiculos().size(); i++){
                DecimalFormat df = new DecimalFormat("0.00");
                df.setRoundingMode(RoundingMode.HALF_DOWN);


            if(LocadoraDados.getVeiculos().get(i).isDisponivel() == true){

                modelo.addRow(new String[]{ 
                    String.valueOf(LocadoraDados.getVeiculos().get(i).getCodigoAuto()),
                    LocadoraDados.getVeiculos().get(i).getTipo(),
                    String.valueOf(df.format(LocadoraDados.getVeiculos().get(i).getValorDiaria())),
                    LocadoraDados.getVeiculos().get(i).getDescricao(),
                    LocadoraDados.getVeiculos().get(i).getPlaca(),
                    LocadoraDados.getVeiculos().get(i).getMarca(),
                    String.valueOf(LocadoraDados.getVeiculos().get(i).getPassageiros()),
                    LocadoraDados.getVeiculos().get(i).getPartida(),
                    "DISPONIVEL"

                });
            }
        }   
        
        tabelaVeiculos.setModel(modelo);
    }//GEN-LAST:event_btDisponiveisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDisponiveis;
    private javax.swing.JButton btLocados;
    private javax.swing.JButton btTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVeiculos;
    // End of variables declaration//GEN-END:variables
}
