/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceUsuario;

import javax.swing.JOptionPane;
import locadoraveiculos.LocadoraDados;
import locadoraveiculos.Veiculo;

/**
 *
 * @author renan
 */
public class Veiculos extends javax.swing.JInternalFrame {
    
    private ListarVeiculos listarVeiculos;
    
    /**
     * Creates new form Veiculos
     * @param indice recebe um indice para abrir no cadastro, caso seja passado -1 como parametro o cadastro será iniciado como novo
     */
    public Veiculos(int indice) {
        initComponents();
        
        if (indice == -1){
            cbDisponivel.setSelected(true);
            ajustarCampos();
            lblCodigo.setText(String.valueOf(LocadoraDados.setCodigoAutomatico()));
        }else{
            preencheCampos(indice);
        }
        
        listarVeiculos = new ListarVeiculos();
        listarVeiculos.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        lblPossuiPartida = new javax.swing.JLabel();
        cbPossuiPartida = new javax.swing.JComboBox<>();
        cbDisponivel = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        lblIndice = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        btNovo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblNumPassageiros = new javax.swing.JLabel();
        txtNumPassageiros = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        btListar = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        cbTipoVeiculo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValorDiaria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        painelPrincipal.setLayout(null);

        lblPossuiPartida.setText("Partida:");
        painelPrincipal.add(lblPossuiPartida);
        lblPossuiPartida.setBounds(10, 224, 58, 14);

        cbPossuiPartida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO" }));
        painelPrincipal.add(cbPossuiPartida);
        cbPossuiPartida.setBounds(72, 221, 47, 20);

        cbDisponivel.setText("Disponível");
        painelPrincipal.add(cbDisponivel);
        cbDisponivel.setBounds(460, 200, 73, 23);

        jLabel5.setText("Indice:");
        painelPrincipal.add(jLabel5);
        jLabel5.setBounds(450, 56, 33, 14);

        lblIndice.setText("(Novo)");
        painelPrincipal.add(lblIndice);
        lblIndice.setBounds(489, 56, 33, 14);

        jLabel6.setText("Marca:");
        painelPrincipal.add(jLabel6);
        jLabel6.setBounds(10, 194, 33, 14);
        painelPrincipal.add(txtMarca);
        txtMarca.setBounds(72, 191, 88, 20);

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        painelPrincipal.add(btNovo);
        btNovo.setBounds(17, 11, 57, 23);

        jLabel7.setText("Código:");
        painelPrincipal.add(jLabel7);
        jLabel7.setBounds(17, 52, 37, 14);

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        painelPrincipal.add(btSalvar);
        btSalvar.setBounds(80, 11, 63, 23);
        painelPrincipal.add(txtDescricao);
        txtDescricao.setBounds(72, 133, 469, 20);

        jLabel4.setText("Placa:");
        painelPrincipal.add(jLabel4);
        jLabel4.setBounds(10, 163, 29, 14);
        painelPrincipal.add(txtPlaca);
        txtPlaca.setBounds(72, 160, 88, 20);

        lblNumPassageiros.setText("Nº Passageiros:");
        painelPrincipal.add(lblNumPassageiros);
        lblNumPassageiros.setBounds(170, 163, 76, 14);

        txtNumPassageiros.setText("4");
        painelPrincipal.add(txtNumPassageiros);
        txtNumPassageiros.setBounds(250, 160, 74, 20);

        lblCodigo.setText("(Novo)");
        painelPrincipal.add(lblCodigo);
        lblCodigo.setBounds(64, 52, 79, 14);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        painelPrincipal.add(btExcluir);
        btExcluir.setBounds(149, 11, 63, 23);

        btListar.setText("Listar");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });
        painelPrincipal.add(btListar);
        btListar.setBounds(218, 11, 59, 23);

        btAnterior.setText("<");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });
        painelPrincipal.add(btAnterior);
        btAnterior.setBounds(434, 11, 41, 23);

        btProximo.setText(">");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });
        painelPrincipal.add(btProximo);
        btProximo.setBounds(481, 11, 41, 23);

        cbTipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARRO", "MOTO" }));
        cbTipoVeiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoVeiculoItemStateChanged(evt);
            }
        });
        cbTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoVeiculoActionPerformed(evt);
            }
        });
        painelPrincipal.add(cbTipoVeiculo);
        cbTipoVeiculo.setBounds(72, 81, 87, 20);

        jLabel1.setText("Tipo:");
        painelPrincipal.add(jLabel1);
        jLabel1.setBounds(10, 81, 24, 14);

        jLabel2.setText("Valor Diária:");
        painelPrincipal.add(jLabel2);
        jLabel2.setBounds(10, 110, 58, 14);

        txtValorDiaria.setText("0,00");
        painelPrincipal.add(txtValorDiaria);
        txtValorDiaria.setBounds(72, 107, 87, 20);

        jLabel3.setText("Descição:");
        painelPrincipal.add(jLabel3);
        jLabel3.setBounds(10, 133, 46, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        limpaCampos();
        lblCodigo.setText(String.valueOf(LocadoraDados.setCodigoAutomatico()));

    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Veiculo veiculo = null;
       

        try{
            
            if(cbTipoVeiculo.getSelectedItem().equals("MOTO")){
                txtNumPassageiros.setText("2");
            }
            
            veiculo = new Veiculo(
                lblCodigo.getText(),
                cbTipoVeiculo.getSelectedItem().toString(),
                txtValorDiaria.getText(),
                txtDescricao.getText(),
                txtPlaca.getText(),
                txtNumPassageiros.getText(),
                cbPossuiPartida.getSelectedItem().toString(),
                txtMarca.getText(),
                cbDisponivel.isSelected()
            );

            if(veiculo.getTipo().equals("MOTO")){
                veiculo.setPassageiros("2");
            }else{
                veiculo.setPartida("SIM");
            }
            
            
                if((getIndice() == -1)){
                

                lblIndice.setText(String.valueOf(LocadoraDados.getVeiculos().size()));
                LocadoraDados.cadastraVeiculo(veiculo);
                
            }else{
                
                int resposta = JOptionPane.showConfirmDialog(null, "Deseja alterar os dados?", "Confirmar ação", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) {
                    
                    LocadoraDados.alteraVeiculo(getIndice(), veiculo);
                    preencheCampos(getIndice());
                }else{
                    preencheCampos(getIndice());
                }

            }
            
            
        }catch(java.lang.IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }

        

    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        if(lblIndice.getText().equals("(Novo)")){
            JOptionPane.showMessageDialog(null, "Não há nada para excluir");
        }else{

            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse registro?", "Receber", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {

                int minIndice = 0, maxIndice, indice, codigo = -1;
                maxIndice = LocadoraDados.getVeiculos().size()-1;

                try{
                    indice = Integer.parseInt(lblIndice.getText());
                    codigo = Integer.parseInt(lblCodigo.getText());
                }catch(NumberFormatException e){
                    indice = maxIndice;
                }

                if(LocadoraDados.verificaExclusaoVeiculo(codigo) == true){

                    if((indice >= 0) && (indice <= maxIndice)){

                        if(maxIndice>0 && indice < maxIndice){
                            LocadoraDados.removeVeiculo(indice);
                            preencheCampos(indice);

                        }else if((indice == 0) && (maxIndice == 0)){
                            LocadoraDados.removeVeiculo(indice);
                            limpaCampos();

                        }else if((indice == 0) && (maxIndice > 0)){

                            LocadoraDados.removeVeiculo(indice);
                            preencheCampos(indice);

                        }else if((indice == maxIndice) && (maxIndice > 0)){

                            LocadoraDados.removeVeiculo(indice);
                            indice --;
                            preencheCampos(indice);

                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Desculpe, esse veiculo não pode ser excluido, pois existem alugueis vinculados a ale");
                }
            }else{

            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
     //   listarVeiculos = new ListarVeiculos();
    //    listarVeiculos.setLocationRelativeTo(null);
     //   listarVeiculos.setVisible(true);
     listarVeiculos = new ListarVeiculos();
     getParent().add(listarVeiculos);
     listarVeiculos.setVisible(true);
     
     
    }//GEN-LAST:event_btListarActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        int indice;
        try{
            indice = Integer.parseInt(lblIndice.getText());
        }catch(java.lang.NumberFormatException e){
            indice = LocadoraDados.getVeiculos().size();
        }

        if (LocadoraDados.getVeiculos().size() == 0){
            JOptionPane.showMessageDialog(null, "Esse é o primeiro registro");
        }else{

            if(indice <= 0){
                JOptionPane.showMessageDialog(null, "Esse é o primeiro registro");
            }else{
                indice --;
                preencheCampos(indice);  //Chama o metodo para preencher os campos
            }

        }
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        int indice;
        try{

            indice = Integer.parseInt(lblIndice.getText());

        }catch(java.lang.NumberFormatException e){
            indice = LocadoraDados.getVeiculos().size();
        }

        if(indice+1 >= LocadoraDados.getVeiculos().size()){
            JOptionPane.showMessageDialog(null, "Esse é o ultimo registro");
        }else{
            indice++;
            preencheCampos(indice);
        }
    }//GEN-LAST:event_btProximoActionPerformed

    
    
    private int getCodigo(){
        int codigo = -1;
        try{
            
            codigo = Integer.parseInt(lblCodigo.getText());
        }catch(NumberFormatException e){
            
            return -1;
        }
        return codigo;
    }
    
    private int getIndice(){
        int indice = -1;
        try{
            
            indice = Integer.parseInt(lblIndice.getText());
        }catch(NumberFormatException e){
            
            return -1;
        }
        return indice;
    }
    
    private void preencheCampos(int indice){
        
        if(indice <0){
            
        }else{
            lblCodigo.setText(String.valueOf(LocadoraDados.getVeiculos().get(indice).getCodigoAuto()));
            cbTipoVeiculo.setSelectedItem(LocadoraDados.getVeiculos().get(indice).getTipo());
            ajustarCampos();
            txtValorDiaria.setText(String.valueOf(LocadoraDados.getVeiculos().get(indice).getValorDiaria()));
            txtDescricao.setText(String.valueOf(LocadoraDados.getVeiculos().get(indice).getDescricao()));
            txtPlaca.setText(String.valueOf(LocadoraDados.getVeiculos().get(indice).getPlaca()));
            txtNumPassageiros.setText(String.valueOf(LocadoraDados.getVeiculos().get(indice).getPassageiros()));
            cbPossuiPartida.setSelectedItem(LocadoraDados.getVeiculos().get(indice).getPartida());
            cbDisponivel.setSelected(LocadoraDados.getVeiculos().get(indice).isDisponivel());
            lblIndice.setText(String.valueOf(indice));
            txtMarca.setText(LocadoraDados.getVeiculos().get(indice).getMarca());
        }
    }
    
    private void limpaCampos(){
        cbTipoVeiculo.setSelectedItem("CARRO");    
        ajustarCampos();
        txtValorDiaria.setText("0,00");
        txtDescricao.setText("");
        txtPlaca.setText("");
        txtNumPassageiros.setText("0");
        cbPossuiPartida.setSelectedItem("NÃO");
        cbDisponivel.setSelected(true);
        lblIndice.setText("(Novo)");
        txtMarca.setText("");
    }
    
    
    private void ajustarCampos(){
        if(cbTipoVeiculo.getSelectedItem().toString().equals("CARRO")){
            cbPossuiPartida.setVisible(false);
            lblPossuiPartida.setVisible(false);
            lblNumPassageiros.setVisible(true);
            txtNumPassageiros.setVisible(true);
        }else if(cbTipoVeiculo.getSelectedItem().toString().equals("MOTO")){
            lblNumPassageiros.setVisible(false);
            txtNumPassageiros.setVisible(false);
            cbPossuiPartida.setVisible(true);
            lblPossuiPartida.setVisible(true);
        }
    }
    
    
    
    private void cbTipoVeiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoVeiculoItemStateChanged
        ajustarCampos();

    }//GEN-LAST:event_cbTipoVeiculoItemStateChanged

    private void cbTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoVeiculoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox cbDisponivel;
    private javax.swing.JComboBox<String> cbPossuiPartida;
    private javax.swing.JComboBox<String> cbTipoVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblIndice;
    private javax.swing.JLabel lblNumPassageiros;
    private javax.swing.JLabel lblPossuiPartida;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNumPassageiros;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtValorDiaria;
    // End of variables declaration//GEN-END:variables
}
